# Generated by Django 6.0.2 on 2026-02-06 23:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la categoría', verbose_name='Descripción')),
                ('campos_extra', models.JSONField(blank=True, default=dict, help_text='Datos específicos por nicho. Ej: {"tipo_medicamento": "controlado"} o {"especie": "perro"}', verbose_name='Campos extra')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa propietaria de la categoría', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(blank=True, help_text='Ej: ml, unidades, caja', max_length=50, verbose_name='Unidad de medida')),
                ('stock_minimo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje (ej: 10.00 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('proveedor', models.CharField(blank=True, max_length=255, verbose_name='Proveedor/Distribuidor')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('lote', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('campos_extra', models.JSONField(blank=True, default=dict, help_text='Ej farmacia: {"principio_activo":"paracetamol"}; veterinaria: {"especie":"gato"}', verbose_name='Campos extra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventario.category', verbose_name='Categoría')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa propietaria del producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('referencia', models.CharField(blank=True, help_text='Número de factura, orden de compra u otra referencia', max_length=100, verbose_name='Referencia')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa responsable del movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='accounts.empresa', verbose_name='Empresa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventario.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
